
export const PROFILE = {
    name: "Zeini Cheikh",
    title: "Student in Information Systems Development",
    email: "zeiny.cheikh.dev@gmail.com",
    github: "https://github.com/Zeini-23025",
    reddit: "https://www.reddit.com/user/Zeini-25",
    cv: "/legacy/cv/ZeinyCV.pdf", // Pointing to legacy location for now
    bio: "Student in 3rd year Information Systems Development. Passionate about web application design, project management, and new technologies. Specialized in robust software solutions."
};

export const SKILLS = [
    { category: "Frontend", items: ["HTML", "CSS", "JavaScript", "React", "Bootstrap"] },
    { category: "Backend", items: ["Python", "PHP", "Java", "Django", "Flask", "Spring"] },
    { category: "Databases", items: ["SQL", "MySQL", "MongoDB"] },
    { category: "DevOps & Tools", items: ["Docker", "Git", "GitHub", "Linux"] }
];

export const PROJECTS = [
    {
        id: "p1",
        title: "Project Management Platform",
        description: "Web platform allowing students to submit internships online and admins to manage assignments.",
        tags: ["HTML", "CSS", "JavaScript", "PHP", "MySQL"],
        type: "Academic"
    },
    {
        id: "p2",
        title: "Real Estate Revenue",
        description: "App for tracking revenue generated by real estate properties and administrative management.",
        tags: ["React", "Django", "Django REST"],
        type: "Academic"
    },
    {
        id: "p3",
        title: "MS-RCPSP Planning",
        description: "Intelligent project planning system using AI to recommend scheduling algorithms.",
        tags: ["AI", "Python", "Operational Research"],
        type: "Academic"
    },
    {
        id: "exp1",
        title: "Online Complaints Management",
        company: "MTINIMA",
        duration: "1 month - 2024",
        description: "Web app for submitting and tracking claims.",
        tags: ["HTML", "CSS", "JS", "PHP", "MySQL"],
        type: "Internship"
    },
    {
        id: "exp2",
        title: "SmarttAssure",
        company: "SMART",
        duration: "2 months - 2025",
        description: "Insurance process management web application.",
        tags: ["React", "Django REST", "JWT", "Swagger", "Bootstrap"],
        type: "Internship"
    },
    {
        id: "exp3",
        title: "Freelance Platform API",
        company: "Elhilal",
        duration: "4 months - 2025",
        description: "REST API development and internal project contribution (agencevoursa.com).",
        tags: ["API REST", "Django"],
        type: "Internship"
    }
];
